services:
  db:
    image: postgres:16.8-alpine3.21
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./init-test_db.sh:/docker-entrypoint-initdb.d/init-test_db.sh
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      timeout: 2s
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        alembic upgrade head &&
        poetry run uvicorn src.main:app --host=${API_HOST} --port=${API_PORT} --reload"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    depends_on:
      - db

  redis:
    image: redis:7.2.7-alpine3.21
    container_name: redis_container
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  pg_data:
