"""change_field_for_User

Revision ID: 01f2e76ff156
Revises: 86f231d21ac3
Create Date: 2025-02-16 13:28:27.564862

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01f2e76ff156"
down_revision: str | None = "86f231d21ac3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("yandex_access_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "yandex_access_token")
    # ### end Alembic commands ###
