"""Initial migrations

Revision ID: 077cb52c0276
Revises:
Create Date: 2025-02-22 07:19:38.241027

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "077cb52c0276"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("categories_pkey")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=250), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("google_access_token", sa.String(length=250), nullable=True),
        sa.Column("yandex_access_token", sa.String(length=250), nullable=True),
        sa.Column("first_name", sa.String(length=250), nullable=True),
        sa.Column("last_name", sa.String(length=250), nullable=True),
        sa.Column("date_joined", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_super_user", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("email", name=op.f("users_email_key")),
        sa.UniqueConstraint("username", name=op.f("users_username_key")),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("pomodoro_count", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("tasks_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("tasks_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("users")
    op.drop_table("categories")
    # ### end Alembic commands ###
