"""delete access token from User

Revision ID: 6472ea031991
Revises: 6da06f85d574
Create Date: 2025-02-14 17:47:43.727216

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6472ea031991"
down_revision: str | None = "6da06f85d574"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "access_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
