"""change User access token str | None

Revision ID: 6da06f85d574
Revises: 2068aed9e5bd
Create Date: 2025-02-14 17:43:14.565268

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6da06f85d574"
down_revision: str | None = "2068aed9e5bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "access_token", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "access_token", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
