"""change_field_for_User

Revision ID: 86f231d21ac3
Revises: 2bc6b71bb97b
Create Date: 2025-02-16 12:08:19.290258

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86f231d21ac3"
down_revision: str | None = "2bc6b71bb97b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
