name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup-python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependecies
        run: pip install poetry && poetry install

      - name: run
        run: poetry run ruff check .
