name: Check by the linter
run-name: "${{ github.actor }} launched linter on  GitHub Actions 🚀"

on:
  workflow_dispatch:

  pull_request:

concurrency:
  group: check-linters
  cancel-in-progress: true


jobs:
  run-linter:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip3 install poetry
          poetry config virtualenvs.create false
          poetry add ruff

      - name: Run linter
        run: poetry run ruff check .
